### ISSUE TITLE
Language Questions

### ISSUE THREAD

**Issue by baymax88** [baymax88/language-assessments#1]
#### Q8. MATCH is to IGNITE as ...

- [x] PEN is to WRITE
- [ ] CAGE is to FREE
- [ ] FIRE is to HOT
- [ ] CRIME is to PUNISH
- [ ] CHAIR is to DESK

#### Q9. SKYSCRAPER is to BUILDING as ...

- [ ] SUGAR is to SALT
- [x] MARS is to PLANET
- [ ] ROOM is to HOUSE
- [ ] DESERT is to JUNGLE
- [ ] COURTYARD is to LOBBY

#### Q10. OCCUPIED is to VACANT as ...

- [ ] BEAUTIFUL is to SIGHT
- [ ] BLISSFUL is to HAPPINESS
- [ ] CONSERVED is to RETAINED
- [x] HONORABLE is to SHAMEFUL
- [ ] MYOPIC is to SHORTSIGHTED

#### Q11. Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.

```
Under her mentor's ______, guided by the mentor's decades of experience,
the new employee quickly developed the skills that she needed to excel in her job
```

- [ ] pilferage
- [ ] suffrage
- [ ] shortage
- [ ] umbrage
- [x] tutelage

#### Q12. Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.

```
The analyst ______ every tool at his disposal in order to manipulate the dataset,
but despite his best efforts, he found that he was unable to fulfill his manager's request.
```

- [ ] compartmentalized
- [ ] advocated
- [x] utilized
- [ ] outmaneuvered
- [ ] vindicated

#### Q13. Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.

```
While opportunities for self-improvement ____,
sometimes a major life event might be needed as a(n) _____ to get started
```

- [ ] amass .. pinnacle
- [ ] actualize .. hurdle
- [ ] rectify .. disturbance
- [ ] surge .. taunt
- [x] abound .. impetus

#### Q14. Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.

```
After a series of steep ascents the bike race ____, mercifully,
on a flat stretch where bikers race for the finish line.
```

- [ ] fulminates
- [ ] culminates
- [x] declines
- [ ] elucidates
- [ ] deliberates

#### Q34.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
Despite her desire to ____ her former employer during a job interview, the candidate chose to speak about her previous workplace in more ____ terms.

- [ ] malign…diplomatic
- [x] disparage…formal
- [ ] diminish…meticulous
- [ ] commend…affable
- [ ] humiliate...conniving

#### Q35.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
Aware that his conduct had been ____, and intent on limiting the fallout from the scandal, the politician decided to resign and leave public office.

- [x] reprehensible
- [ ] irreproachable
- [ ] defensible
- [ ] petulant
- [ ] fortuitous

#### Q40.  Choose the word that is most nearly OPPOSITE to the word in capital letters.
OBFUSCATE

- [ ] coordinate
- [ ] facilitate
- [x] demystify
- [ ] bamboozle
- [ ] enunciate

#### Q41.  Choose the word that is most nearly OPPOSITE to the word in capital letters.
INTRICATE

- [ ] strict
- [x] simple
- [ ] ugly
- [ ] complex
- [ ] static

#### Q42.  CASTIGAGE is to PUNISHMENT as..

- [ ] APPROVE is to CITATION
- [ ] DEVOTE is to ANIMOSITY
- [x] ADVISE is to MENTORSHIP
- [ ] REPORT is to VENGEANCE
- [ ] CLARIFY is to ENDOWMENT

#### Q43.  IRATE is to ANGER as..

- [ ] MUTINOUS is to COMPLIANCE
- [x] JOYOUS is to GLEE
- [ ] INSENSITIVE is to FRAGILITY
- [ ] ACTUAL is to LIKELIHOOD
- [ ] WEALTHY is to POVERTY

#### Q44. Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
Rumors can form at work when people share ____ claims about their coworkers, which can lead to a(n) ____ workplace culture.

- [ ] defiant..wary
- [ ] flattering..aloof
- [x] baseless..hostile
- [ ] egregious..collegial
- [ ] legitimate..asocial

#### Q51. TREE is to SEED as ...
- [ ] BABY is to ADULT
- [x] BUTTERFLY is to CATERPILLAR
- [ ] SCRIPT is to MOVIE
- [ ] STUDENT is to TEACHER
- [ ] BRANCH is to FOREST

#### Q52. MANGO is to FRUIT as ...
- [ ] BIKE is to CAR
- [ ] SPEAK is to LISTEN
- [ ] BOX is to STACK
- [ ] DOCTOR is to HOSPITAL
- [x] BOOT is to SHOE

#### Q53.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
While the restaurant has always been popular due to the high ____ of its service, the replacement of its old head chef was soon followed by a noticeable improvement in its food as well.

- [ ] abridgement
- [ ] tact
- [ ] maturity
- [x] caliber
- [ ] permanence

#### Q54.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
Given the positive response to their closing presentation, the sales team felt that the meeting had _____ in success.

- [ ] perpetuated
- [ ] commenced
- [ ] stagnated
- [x] culminated
- [ ] recanted

#### Q55.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
Having already listened to many hours of her friend's ____ attempts at poetry, she wasn't sure if she could _____ another bad poem.

- [ ] sophisticated .. resent
- [ ] virtuoso .. abide
- [x] rudimentary .. tolerate
- [ ] redemptive .. purport
- [ ] secretive .. transmit

#### Q56.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
The company needed to find a way to quantify and ___ the productivity of its employees in order to decide who deserved raises that year.

- [ ] correspond
- [ ] stabilize
- [ ] mitigate
- [ ] counteract
- [x] measure

#### Q57.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
Taking issue with media reports, the president _____ that she had no plans to step down and _____ claims that her office was guilty of corruption.

- [ ] averred .. detailed
- [x] affirmed .. dismissed
- [ ] alleged .. derided
- [ ] admitted .. disputed
- [ ] claimed .. buttressed

#### Q58.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
The beloved celebrity spokesperson, who was featured in the dramatic advertisement for the well-known charity, _____ any and all sympathetic viewers to make a donation to the worthy cause.

- [ ] defrauded
- [x] implored
- [ ] exhumed
- [ ] articulated
- [ ] entrapped

#### Q59.  Choose the word that is most nearly OPPOSITE to the word in capital letters.
ALLURE

- [ ] belligerence
- [ ] indifference
- [x] repulsion
- [ ] reluctance
- [ ] persuasiveness

#### Q60.  Choose the word that is most nearly OPPOSITE to the word in capital letters.
PROLIFIC

- [ ] fruitful
- [ ] unknown
- [ ] obscure
- [x] unproductive
- [ ] secretive

#### Q61. DELUSIONAL is to GROUNDED as ...
- [ ] OVERBLOWN is to EMBELLISHED
- [ ] AUSTERE is to SPARTAN
- [ ] UPBEAT is to HOPEFUL
- [x] ESTEEMED is to SEEDY
- [ ] DEEP is to BROAD

#### Q62. CULPABLE is to BLAME as ...
- [ ] EDIBLE is to TASTE
- [ ] MALLEABLE is to CENSURE
- [ ] MENIAL is to DISGUST
- [ ] PENAL is to INCARCERATION
- [x] LAUDABLE is to PRAISE

#### Q63.  Choose the word or words that, when inserted in the sentence to replace the blank or blanks, best fits the meaning of the sentence.
Based on the _____ behavior and _____ toward service staff exhibited by the job applicant before his interview, the hiring manager decided not to move forward with his application.

- [ ] gregarious .. conceit
- [ ] atrocious .. pity
- [ ] obnoxious .. chivalry
- [ ] ambitious .. disdain
- [x] supercilious .. insolence

**Comment by Taara-Sinh-Aatrey** [comment]
61 is wrong I guess. The correct answer should be ```ESTEEMED is to SEEDY```

**Comment by shiv** [comment]
Yes, you are right @Taara-Sinh-Aatrey, the correct answer is ```ESTEEMED is to SEEDY```.

**Comment by baymax88** [comment]
Yes, you guys are right!

**Comment by emecandoit** [comment]
Q#44 is baseless and hostile
